### ISSUE TITLE
Some problem about use self defined params in config.toml

### ISSUE THREAD

**Issue by Vickey-Wu** [themefisher/parsa-hugo#12]
1. Is there some documents for adding self defind params in config.toml?

    2.How can i use other icon , such as fa-icon rather ti-icon. I use fa-icon, but it seems take no effect. Is there anything else i should change at the same time?

    3. How can i adjust image width in my markdown file

**Comment by Somrat37** [comment]
1. this is a free template and we comment in the code. that's why there is no other documentation.

2. We used themify icon pack in this template. so you can't use fa-icon, if you need more icon then visit : https://themify.me/themify-icons

3. In markdown file. the image will adjust automatically.

**Comment by Vickey-Wu** [comment]
I see, thanks a lot
