### ISSUE TITLE
An empty post in the Latest Post list top

### ISSUE THREAD

**Issue by SnailZSJ** [themefisher/parsa-hugo#14]
There is always an empty post in the Latest Post list. It has no cover image, no title, and the creation time show as "Jan 01, 0001".

**Comment by Somrat37** [comment]
hey there, Can you give me any references?

**Comment by SnailZSJ** [comment]
Thanks you for your reply. I solved the problem.

Because I created a new "post" folder in the "content" directory, but did not create a new "_index.md" file in the "post" folder, there will be an empty top post in the Latest post list.

I solved this problem by creating a new "_index.md" file in the "post" directory. You can assess whether this is a problem that needs to be solved. This issue can now be closed. Thank you.
