### ISSUE TITLE
Why I can't use search to search my post content?

### ISSUE THREAD

**Issue by Vickey-Wu** [themefisher/parsa-hugo#15]
Why I can't use search to search my post content? I search anything it always return "No matches found", Is there some rule that I must obey in markdown file?

**Comment by Vickey-Wu** [comment]
> Why I can't use search to search my post content? I search anything it always return "No matches found", Is there some rule that I must obey in markdown file?

I can search now when I move my markdown file to `content/` directory not my `content/posts/` directory, I don't know why it can search part of Chinese words but not all.

**Comment by Somrat37** [comment]
hey there. parsa is a blog template, that's why we create the blogs direct content directory. so it can only search when it has no subfolder in content.

**Comment by jDeppen** [comment]
To search for subfolder content, I changed this line
```{{- range .Pages -}}```
to
```{{- range .Site.RegularPages -}}```

**/themes/parsa-hugo/layouts/_default/index.json**

**Comment by Vickey-Wu** [comment]
> To search for subfolder content, I changed this line
> `{{- range .Pages -}}`
> to
> `{{- range .Site.RegularPages -}}`
> 
> **/themes/parsa-hugo/layouts/_default/index.json**

It is awsome! Thanks a lot!
