### ISSUE TITLE
The theme is not applied with Netlify hosting

### ISSUE THREAD

**Issue by newt0** [themefisher/parsa-hugo#18]
1. Fork repository(succeeded!)

2. Add my repository in Forestry and change the base url in configuration.(succeeded!)

3.Setup and host the site with Netlify
I succeeded to deploy, but no CSS file is applied. Like this(https://newthugo.netlify.app/).

How can I fix it?
I’ve tried to manage it by myself, but It was hard for me.

**Comment by mehedi-sharif** [comment]
It seems , the base url is not correct in config file .

Mehedi Sharif
Themefisher
Themefisher@gmail.com
www.themefisher.com

**Comment by newt0** [comment]
THANK YOU VERY MUCH!
After fixing baseURL, my site works well.
I feel like you're my savior because I was struggling for 5 hours.
