### ISSUE TITLE
The theme is wrong loaded

### ISSUE THREAD

**Issue by edufariasud** [themefisher/parsa-hugo#19]
I followed the correct sequence: github, forestry, netlify.
Any idea what might have happened?

![parsa-hugo](https://user-images.githubusercontent.com/22399021/80868042-59da6e80-8c6e-11ea-8f0e-4c08af2223ea.png)

**Comment by mehedi-sharif** [comment]
Please update your base url in config.toml file

Mehedi Sharif
Themefisher
Themefisher@gmail.com
www.themefisher.com

**Comment by Somrat37** [comment]
Did you fix this issue? I am going to close this issue if you need any more support, then you can reopen this issue or create a new issue. 

Thanks for being with themefisher.
