### ISSUE TITLE
Is it possible to add or remove class="rounded" from the image of a particular article?

### ISSUE THREAD

**Issue by newt0** [themefisher/parsa-hugo#20]
Is it possible to add or remove `class="rounded"` from the image of a particular article?

I'd like to add `class="rounded"` to the image in the article introducing the product, while in the column, I'd like to focus on the text of the article without making the image stand out

**Comment by Somrat37** [comment]
I can't get your problem properly. By the way, if you want to remove this class from a particular post, then you need to do some tweaks with Hugo.  You can set `if condition` on the class, so when you enable it on the post frontmatter only then it will add to your post.

**Comment by newt0** [comment]
Sorry, I misspoke` float-left` as `rounded`.
But I can now only apply the `float-left` to images in arbitrary articles using the if statement!.
Thank you so much!
