### ISSUE TITLE
Is it possible to have the article return only the value when `src="{{.Params.Image | absURL }}"` is true and show the default image when` src="{{.Params.Image | absURL }}" `is false?

### ISSUE THREAD

**Issue by newt0** [themefisher/parsa-hugo#21]
Is it possible to have the article return only the value when `src="{{.Params.Image | absURL }}"` is true and show the default image when` src="{{.Params.Image | absURL }}" `is false?

For example, when acquiring images from Contentful in Nuxt.js, we can use the ternary operator to write the following inside the <img> tag.

`<img :src="post.fields.image ? post.fields.image.fields.file.url : 'The default image URL' ">`

Or use Nuxt.js(Vue.js) conditional branching to determine if the image source is true.
```
<img v-if="post.fields.image" :src="post.fields.image.fields.file.url">
<img v-else="" src="デフォルトにする画像のURL">

```

Can't we use ternary operators in Go?

**Comment by Somrat37** [comment]
Yes, it is possible,

`
{{ if .Params.Image }} <img src="{{.Params.Image | absURL }}> {{ end}}
`

**Comment by newt0** [comment]
It perfectly works!
Thank you so much.
