### ISSUE TITLE
Instagram feed (instafeed) need update

### ISSUE THREAD

**Issue by monomono2** [themefisher/parsa-hugo#25]
The instagram feed not is functional.
I replace the [instafeed.min.js](https://github.com/themefisher/parsa-hugo/blob/master/static/plugins/instafeed/instafeed.min.js) by [instafeed.min.js ](https://github.com/stevenschobert/instafeed.js/blob/master/dist/instafeed.min.js) and that is functional.

**Comment by developer-evan** [comment]
hey there, if you want, you can create a pull request, or I will do it in the next update, thanks
