### ISSUE TITLE
need a new endpoint from Instagram 

### ISSUE THREAD

**Issue by newt0** [themefisher/parsa-hugo#28]
The current Instagram endpoint is finished, so the site need a new endpoint.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/56229817/88645107-b7137e00-d0fe-11ea-94a7-238a0b491719.png">

**Comment by developer-evan** [comment]
This issue has been fixed, please download the latest code.

Also if you like our theme, a star to the repository would be amazing.
