### ISSUE TITLE
How to add a Drop Down "More" Menu + Pages

### ISSUE THREAD

**Issue by stephenajulu** [themefisher/parsa-hugo#31]
Hi, how are you?
Could you kindly help me.
I am interested in creating pages e.g Privacy Policy, Terms and Conditions and more and add them to the menu.
Problem is i don't know if the method i am thinking about will work(the method: create a new folder, name it after the page create a new md file copy the about frontmatter and paste it  and write the rest), i don't know how to import it into forestry for easier editing when i final start adding writers and i don't know how to add them to the menu through a "more" dropdown menu item.
Kindly help me.

**Comment by developer-evan** [comment]
Hey there, you can find all the solutions from here https://docs.gethugothemes.com/guide/
