### ISSUE TITLE
Insta feed not showing up

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/parsa-hugo#32]
I checked everywhere but there is no insta feed showing up in the site. I already got my access token from instagram. Where does the site show the insta feed?

**Comment by Aarekaz** [comment]
its says ``` Error from Instagram: The access_token provided is invalid.
    at e.parse (instafeed.min.js:2)
    at recent?access_token=IGQVJXNkFrVXVpMjItd0tndF9mSHdJUUJUdlRIc1Q2bl9EeGh4cmJZATmJpQlJIU3MwZA1owWVRMdEd4aU1HLTBBT1JNOURVaFFJd1NNeDJRQXBYdld1a0x3aGZAyUzZApbm9xZAlNoOGZAuQ2JOaWU4ZA1M0bQZDZD&callback=instafeedCache727ffdb5686d6209.parse:1```

**Comment by developer-evan** [comment]
hey there, please download the latest code, it has instafeed enabled.
