### ISSUE TITLE
post-thumb in forestry

### ISSUE THREAD

**Issue by robertoioi** [themefisher/parsa-hugo#38]
For each new post I create, I can't see any thumb of the post I uploaded: I can see only "post-thumb".

![image](https://user-images.githubusercontent.com/74615274/107346789-645f4980-6ac5-11eb-82b9-5a33ba9c8d08.png)
Help! 
ps: analyzing the html for the examples there is a src like this: example.com/folder/to/imgs/image.jpg, while for the new posts I see only example.com/ ... btw, I uploaded the media and I can see them on Forestry (from repo).

**Comment by somratpro** [comment]
Hello @robertoioi 

We just update the theme. Please download the latest code. It will solve your issue I guess.
