### ISSUE TITLE
is Dark theme avaible?

### ISSUE THREAD

**Issue by raifpy** [themefisher/parsa-hugo#40]
or how can i enable dark theme?

**Comment by somratpro** [comment]
Hello @raifpy 

Dark theme is not available or this template. but you can make it dark by changing the value of css. https://docs.gethugothemes.com/guide/#colors-and-fonts  follow this doc

**Comment by raifpy** [comment]
> Hello @raifpy
> 
> Dark theme is not available or this template. but you can make it dark by changing the value of css. https://docs.gethugothemes.com/guide/#colors-and-fonts follow this doc

Thank you
