### ISSUE TITLE
"feature" type image size

### ISSUE THREAD

**Issue by whanley** [themefisher/parsa-hugo#42]
The four `type="feature"` tiles on my parsa-themed [homepage](https://willhanley.net/) (the four tiles with "Read More" boxes) lead to pages with massive images at the head ([example](https://willhanley.net/featured/tutorials/)). How can I resize the images on the target pages? 

Code is [here](https://github.com/whanley/website/tree/gh-pages).

**Comment by somratpro** [comment]
Hello @whanley 

Thanks for choosing our theme, you can use a smaller image like (474*545)px to get a perfect fit like the [demo](https://demo.gethugothemes.com/parsa/organize-your-life.2/) has.

**Comment by whanley** [comment]
The images ([here](https://github.com/whanley/website/tree/gh-pages/static/images/featured-post)) are already that size. What else can I do?

**Comment by whanley** [comment]
Okay, I think I've solved it by editing `/themes/parsa/layouts/_default/single.html`. I added this attribute to the `img` tag for regular (not post) pages: `class="img-fluid rounded float-left mr-5 mb-4"`
