### ISSUE TITLE
how to set up contact_form

### ISSUE THREAD

**Issue by dedi0003** [themefisher/parsa-hugo#43]
Hi, I acknowledge that there is **contact_form_action** field in config.toml. I want to use formspree.io to redirect the message submitted by users to my email address. 
I already modify contact.md as required by formspree. My question is what do I need to fill in the contact_form_action field in config.toml?

**Comment by somratpro** [comment]
Hello @dedi0003 

Please read this doc: https://docs.gethugothemes.com/guide/#contact-and-subscription-form

**Comment by dedi0003** [comment]
Hi Somrat, thanks for your reply. I already followed the guide but when I clicked on submit button, it then open a new window of formspree: "Form should POST - Make sure your form has the method="POST" attribute"

**Comment by somratpro** [comment]
Hello @dedi0003 

We are sorry for this bug, we fixed it, now you can download the latest code and setup successfully contact form, thank you
