### ISSUE TITLE
Remove "Read More" from Featured posts (desktop and moobile)

### ISSUE THREAD

**Issue by wondercomm** [themefisher/parsa-hugo#45]
Hi, 

I was able to edit the desktop layout by editing "layouts/homepage/single.html" ' removed the lines where it says "read more". 

I wanted to know how do I remove the "read more" button on mobile layout?

**Comment by somratpro** [comment]
Hello @wondercomm 

I want to let you know that "layouts/homepage/single.html" is just for showing the demo of two homepages, you need to customize `index.html` file to affect your homepage. https://github.com/themefisher/parsa-hugo/blob/66ebabfe0cfffb98648abed0b48c95a8adb6bc19/layouts/index.html#L16 This line is the featured post layout button.

**Comment by wondercomm** [comment]
Thank you. That is what I did  - eventually figured it out. :) Appreciate the reply!
