### ISSUE TITLE
Writing in markdown.

### ISSUE THREAD

**Issue by Dabs-Cedric** [themefisher/parsa-hugo#56]
I noticed that when writing a text in markdown, line breaks are almost not possible.
It is only possible to make a writing block and to skip one or two lines to create another paragraph.
But I found out that in the css, you just have to remove the margin on the .content to get a better presentation of the text.

**Comment by tfsomrat** [comment]
Hello @Dabs-Cedric 

I have added the functionality to insert line-break as `<br>`. you can download the latest version and try it. thank you

**Comment by Dabs-Cedric** [comment]
Ok, thanks.
