### ISSUE TITLE
Trying to understand the license 

### ISSUE THREAD

**Issue by gayanhewa** [themefisher/parsa-hugo#57]
The Readme mentions the code is released under MIT but the design is not. Are we able to use this theme for commercial purposes 🤔 under the existing MIT license

**Comment by mehedi-sharif** [comment]
Yes, you can use the theme, but we don't have the images license to share, so you need to replace all of the images. thank you

**Comment by gayanhewa** [comment]
🙇🏼 thanks for clarifying @mehedi-sharif
