### ISSUE TITLE
Instagram access token

### ISSUE THREAD

**Issue by nchelaru** [themefisher/parsa-hugo#7]
Hello!

Great work on this theme! :)

I'm wondering how I can get an access token for my Instagram account, for the slider at the bottom of the home page?

I am seeing on this page: https://www.instagram.com/developer/

> "UPDATE: Starting October 15, 2019, new client registration and permission review on Instagram API platform are discontinued in favor of the Instagram Basic Display API."

How does this affect this functionality?

Thank you very much!

**Comment by themefisherDev** [comment]
You can get help from here : https://youtu.be/fGMk8daxF08
